services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: estagios_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-estagios_db}
      POSTGRES_USER: ${POSTGRES_USER:-estagios_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-estagios_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - estagios_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-estagios_user} -d ${POSTGRES_DB:-estagios_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação Django
  web:
    build: .
    container_name: estagios_web
    restart: unless-stopped
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-me-in-production}
      - DATABASE_URL=postgresql://${POSTGRES_USER:-estagios_user}:${POSTGRES_PASSWORD:-estagios_pass}@db:5432/${POSTGRES_DB:-estagios_db}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-estagios_db}           # <— adicione
      - POSTGRES_USER=${POSTGRES_USER:-estagios_user}     # <— adicione
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-estagios_pass} # <— adicione
      - SETUP_INITIAL_DATA=true
    volumes:
      - ./:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - estagios_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin para administração do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: estagios_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@estagios.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - estagios_network

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: estagios_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - estagios_network
    command: redis-server --appendonly yes

  # Nginx para proxy reverso (produção)
  nginx:
    image: nginx:alpine
    container_name: estagios_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/var/www/static
      - ./media:/var/www/media
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - estagios_network
    profiles:
      - production

# Bloco de volumes deve ficar NO MESMO NÍVEL de `services:`
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  redis_data:
    driver: local

networks:
  estagios_network:
    driver: bridge
