# Generated by Django 4.2.7 on 2025-06-29 01:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve estar no formato: 00.000.000/0000-00', regex='^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$')], verbose_name='CNPJ')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (00) 00000-0000', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável')),
                ('email_responsavel', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Responsável')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['nome_empresa'],
            },
        ),
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato: (00) 00000-0000', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('periodo', models.CharField(max_length=20, verbose_name='Período')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')], verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='Status')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Estagiário',
                'verbose_name_plural': 'Estagiários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticasSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_calculo', models.DateTimeField(auto_now=True, verbose_name='Data do Cálculo')),
                ('total_estagiarios', models.PositiveIntegerField(default=0, verbose_name='Total de Estagiários')),
                ('estagiarios_ativos', models.PositiveIntegerField(default=0, verbose_name='Estagiários Ativos')),
                ('total_estagios', models.PositiveIntegerField(default=0, verbose_name='Total de Estágios')),
                ('estagios_em_andamento', models.PositiveIntegerField(default=0, verbose_name='Estágios em Andamento')),
                ('total_convenios', models.PositiveIntegerField(default=0, verbose_name='Total de Convênios')),
                ('convenios_ativos', models.PositiveIntegerField(default=0, verbose_name='Convênios Ativos')),
                ('total_documentos', models.PositiveIntegerField(default=0, verbose_name='Total de Documentos')),
                ('notificacoes_nao_lidas', models.PositiveIntegerField(default=0, verbose_name='Notificações Não Lidas')),
            ],
            options={
                'verbose_name': 'Estatísticas do Sistema',
                'verbose_name_plural': 'Estatísticas do Sistema',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('INFO', 'Informação'), ('ALERTA', 'Alerta'), ('URGENTE', 'Urgente')], default='INFO', max_length=10, verbose_name='Tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.estagiario', verbose_name='Estagiário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Estagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(max_length=200, verbose_name='Supervisor')),
                ('supervisor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Supervisor')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária (horas)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado'), ('SUSPENSO', 'Suspenso')], default='EM_ANDAMENTO', max_length=15, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estagios', to='core.convenio', verbose_name='Convênio')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estagios', to='core.estagiario', verbose_name='Estagiário')),
            ],
            options={
                'verbose_name': 'Estágio',
                'verbose_name_plural': 'Estágios',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('TERMO_COMPROMISSO', 'Termo de Compromisso'), ('PLANO_ESTAGIO', 'Plano de Estágio'), ('RELATORIO', 'Relatório'), ('AVALIACAO', 'Avaliação'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to=core.models.upload_documento_path, verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('estagio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.estagio', verbose_name='Estágio')),
                ('usuario_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário que fez o Upload')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_upload'],
            },
        ),
    ]
