name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: estagios_db
          POSTGRES_USER: estagios_user
          POSTGRES_PASSWORD: estagios_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://estagios_user:estagios_pass@localhost:5432/estagios_db
      SECRET_KEY: test-secret
      DEBUG: "True"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
      - name: Run Black
        run: black --check .
      - name: Run flake8
        run: flake8 .
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings